CREATE TABLE `metas_operacionais` (
	`id` int AUTO_INCREMENT NOT NULL,
	`anoVigencia` int,
	`metaEntregaNoPrazoPct` decimal(5,2) DEFAULT '90.00',
	`metaMaxRetrabalhosMes` int,
	`metaMaxRetrabalhoPct` decimal(5,2) DEFAULT '5.00',
	`metaFaturamentoMensal` decimal(14,2) DEFAULT '425000.00',
	`metaFaturamentoAnual` decimal(16,2),
	`metaLucratividadePct` decimal(5,2),
	`metaLucratividadeValor` decimal(14,2),
	`metaMetrosSoldadosMes` int,
	`metaCapacidadeSoldaMin` int,
	`metaCapacidadeSoldaMax` int,
	`metaMaxPrejuizoRetrabalhoMes` decimal(12,2),
	`metaMaxPrejuizoRetrabalhoPct` decimal(5,2),
	`metaOsPorColaboradorDia` decimal(6,2),
	`metaRetrabalhosPorColaboradorMes` int,
	`metaTicketMedio` decimal(10,2) DEFAULT '3000.00',
	`metaMaxMetrosTerceirizadosMes` int,
	`metaMaxPercTerceirizacao` decimal(5,2),
	`observacoes` text,
	`ativo` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `metas_operacionais_id` PRIMARY KEY(`id`)
);
