CREATE TABLE `financeiros_mensais` (
	`id` int AUTO_INCREMENT NOT NULL,
	`mes` int NOT NULL,
	`ano` int NOT NULL,
	`receita_bruta` decimal(14,2) NOT NULL DEFAULT '0',
	`receita_operacional` decimal(14,2) NOT NULL DEFAULT '0',
	`receita_financeira` decimal(14,2) NOT NULL DEFAULT '0',
	`despesas_total` decimal(14,2) NOT NULL DEFAULT '0',
	`despesas_fixas` decimal(14,2) NOT NULL DEFAULT '0',
	`despesas_variaveis` decimal(14,2) NOT NULL DEFAULT '0',
	`despesas_pessoal` decimal(14,2) NOT NULL DEFAULT '0',
	`despesas_financeiras` decimal(14,2) NOT NULL DEFAULT '0',
	`despesas_impostos` decimal(14,2) NOT NULL DEFAULT '0',
	`lucro_gruto` decimal(14,2) NOT NULL DEFAULT '0',
	`lucro_operacional` decimal(14,2) NOT NULL DEFAULT '0',
	`lucro_liquido` decimal(14,2) NOT NULL DEFAULT '0',
	`entradas` decimal(14,2) NOT NULL DEFAULT '0',
	`saidas` decimal(14,2) NOT NULL DEFAULT '0',
	`saldo_mes` decimal(14,2) NOT NULL DEFAULT '0',
	`fonte` varchar(64) DEFAULT 'manual',
	`fonte_arquivo` varchar(256),
	`observacoes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `financeiros_mensais_id` PRIMARY KEY(`id`)
);
