import { describe, expect, it } from "vitest";
import { extrairRegioesCorSvg } from "../services/cpqCoresMateriais";

const corpo = '<path fill="#fecb01" d="M0 0 L100 0 L100 40 L0 40 Z"/><path fill="#1c3f94" d="M10 10 L50 10 L50 30 L10 30 Z"/>';

describe("leitura das cores da arte vetorizada", () => {
  it("aceita o SVG cru do Vectorizer.AI, com <?xml?>, DOCTYPE simples e comentário", () => {
    const svg = `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by Vectorizer.AI -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 40" width="100" height="40">${corpo}</svg>`;
    const regioes = extrairRegioesCorSvg(svg);
    expect(regioes).toHaveLength(2);
    expect(regioes.map(item => item.corHex)).toEqual(["#fecb01", "#1c3f94"]);
    expect(regioes.every(item => item.tipoCor === "solida")).toBe(true);
  });

  it("continua recusando DOCTYPE com entidades e diz o motivo", () => {
    const svg = `<!DOCTYPE svg [<!ENTITY x "y">]><svg viewBox="0 0 10 10">${corpo}</svg>`;
    expect(() => extrairRegioesCorSvg(svg)).toThrow(/DOCTYPE com entidades/);
  });

  it("lê a cor de caminhos com transparência parcial e ignora os quase invisíveis", () => {
    const svg = '<svg viewBox="0 0 10 10">'
      + '<path fill="#ff0000" fill-opacity="0.5" d="M0 0 L9 0 L9 9 Z"/>'
      + '<path fill="#00ff00" opacity="0.99" d="M0 0 L9 0 L9 9 Z"/>'
      + '<path fill="#0000ff" style="fill-opacity:0.1" d="M0 0 L9 0 L9 9 Z"/></svg>';
    const regioes = extrairRegioesCorSvg(svg);
    expect(regioes.map(item => [item.corHex, item.tipoCor])).toEqual([
      ["#ff0000", "solida"], ["#00ff00", "solida"], [null, "desconhecida"],
    ]);
  });

  it.each([
    ['<svg viewBox="0 0 10 10"><style>.a{fill:red}</style>' + corpo + "</svg>", /elementos não suportados/],
    ['<svg viewBox="0 0 10 10"><g transform="scale(2)">' + corpo + "</g></svg>", /transformações/],
  ])("recusa com o motivo exato: %#", (svg, motivo) => {
    expect(() => extrairRegioesCorSvg(svg)).toThrow(motivo);
  });
});
