/**
 * Catálogo de adesivos Imprimax (cores sólidas) extraído do "Catálogo com visual 05/08/2026 V01" enviado pelo usuário.
 * - Nome da cor, linha e acabamento: legendas e páginas de apresentação do catálogo.
 * - corHex: mediana da cor da bobina na foto do catálogo (aproximação de tela; o próprio catálogo avisa que a cor varia
 *   conforme o monitor e manda conferir o catálogo físico). Não é Pantone nem CMYK oficiais.
 * - codigo: identificador interno do Radrasys (IMX-LINHA-COR). O PDF não traz o código de produto da Imprimax.
 * - Não inclui preço, transmissão de luz nem Pantone/CMYK, que o catálogo não informa.
 * Todas as linhas listadas são PVC calandrado polimérico de 80 micra (Color Max e Cristal Color: 80/100 micra), exceto onde o tipo indica translúcido.
 */
export const IMPRIMAX_CATALOGO_VERSAO = "Catálogo 05/08/2026 V01";

export type ImprimaxItemPadrao = {
  codigo: string;
  linha: string;
  nomeCor: string;
  tipoVinil: "monomerico" | "polimerico" | "translucido";
  acabamento: string;
  corHex: string;
  paginaCatalogo: number;
};

export const IMPRIMAX_CATALOGO_PADRAO: ReadonlyArray<ImprimaxItemPadrao> = [
  { codigo: "IMX-GOLD-MAX-BRANCO", linha: "Gold Max", nomeCor: "Branco", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#E0E8E9", paginaCatalogo: 8 },
  { codigo: "IMX-GOLD-MAX-CINZA-CLARO", linha: "Gold Max", nomeCor: "Cinza Claro", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#8D9A99", paginaCatalogo: 9 },
  { codigo: "IMX-GOLD-MAX-PRATA", linha: "Gold Max", nomeCor: "Prata", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#7F8D8E", paginaCatalogo: 10 },
  { codigo: "IMX-GOLD-MAX-PRATA-ALUMINIO", linha: "Gold Max", nomeCor: "Prata Alumínio", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#8C9999", paginaCatalogo: 11 },
  { codigo: "IMX-GOLD-MAX-CINZA-MEDIO", linha: "Gold Max", nomeCor: "Cinza Médio", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#677678", paginaCatalogo: 12 },
  { codigo: "IMX-GOLD-MAX-PRATA-ALUMINIO-ESCURO", linha: "Gold Max", nomeCor: "Prata Alumínio Escuro", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#4B5758", paginaCatalogo: 13 },
  { codigo: "IMX-GOLD-MAX-CINZA-ESCURO", linha: "Gold Max", nomeCor: "Cinza Escuro", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#2E3537", paginaCatalogo: 14 },
  { codigo: "IMX-GOLD-MAX-GRAFITE", linha: "Gold Max", nomeCor: "Grafite", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#44535B", paginaCatalogo: 15 },
  { codigo: "IMX-GOLD-MAX-PRETO", linha: "Gold Max", nomeCor: "Preto", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#020508", paginaCatalogo: 16 },
  { codigo: "IMX-GOLD-MAX-CHOCOLATE", linha: "Gold Max", nomeCor: "Chocolate", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#1C080D", paginaCatalogo: 17 },
  { codigo: "IMX-GOLD-MAX-OURO", linha: "Gold Max", nomeCor: "Ouro", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#BB7125", paginaCatalogo: 18 },
  { codigo: "IMX-GOLD-MAX-CREME", linha: "Gold Max", nomeCor: "Creme", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#D5B68A", paginaCatalogo: 19 },
  { codigo: "IMX-GOLD-MAX-BEGE", linha: "Gold Max", nomeCor: "Bege", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#CFAB90", paginaCatalogo: 20 },
  { codigo: "IMX-GOLD-MAX-BEGE-ESCURO", linha: "Gold Max", nomeCor: "Bege Escuro", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#8C5223", paginaCatalogo: 21 },
  { codigo: "IMX-GOLD-MAX-AMARELO-OURO", linha: "Gold Max", nomeCor: "Amarelo Ouro", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#FFA837", paginaCatalogo: 22 },
  { codigo: "IMX-GOLD-MAX-AMARELO-MEDIO", linha: "Gold Max", nomeCor: "Amarelo Médio", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#FFBC3C", paginaCatalogo: 23 },
  { codigo: "IMX-GOLD-MAX-AMARELO-MILANO", linha: "Gold Max", nomeCor: "Amarelo Milano", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#FFDD49", paginaCatalogo: 24 },
  { codigo: "IMX-GOLD-MAX-LARANJA-BOTANICO", linha: "Gold Max", nomeCor: "Laranja Botânico", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#FF8142", paginaCatalogo: 25 },
  { codigo: "IMX-GOLD-MAX-LARANJA", linha: "Gold Max", nomeCor: "Laranja", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#FF5C25", paginaCatalogo: 26 },
  { codigo: "IMX-GOLD-MAX-LARANJA-ESCURO", linha: "Gold Max", nomeCor: "Laranja Escuro", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#D83B1C", paginaCatalogo: 27 },
  { codigo: "IMX-GOLD-MAX-TERRACOTA", linha: "Gold Max", nomeCor: "Terracota", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#C93F1E", paginaCatalogo: 28 },
  { codigo: "IMX-GOLD-MAX-VERMELHO-TOMATE", linha: "Gold Max", nomeCor: "Vermelho Tomate", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#FF351E", paginaCatalogo: 29 },
  { codigo: "IMX-GOLD-MAX-VERMELHO-FOGO", linha: "Gold Max", nomeCor: "Vermelho Fogo", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#F22C18", paginaCatalogo: 30 },
  { codigo: "IMX-GOLD-MAX-VERMELHO-VIVO", linha: "Gold Max", nomeCor: "Vermelho Vivo", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#A72118", paginaCatalogo: 31 },
  { codigo: "IMX-GOLD-MAX-VINHO", linha: "Gold Max", nomeCor: "Vinho", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#451A26", paginaCatalogo: 32 },
  { codigo: "IMX-GOLD-MAX-ROSA-CLARO", linha: "Gold Max", nomeCor: "Rosa Claro", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#FD7DB7", paginaCatalogo: 33 },
  { codigo: "IMX-GOLD-MAX-PINK", linha: "Gold Max", nomeCor: "Pink", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#DE3593", paginaCatalogo: 34 },
  { codigo: "IMX-GOLD-MAX-VIOLETA", linha: "Gold Max", nomeCor: "Violeta", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#361E5C", paginaCatalogo: 35 },
  { codigo: "IMX-GOLD-MAX-LILAS", linha: "Gold Max", nomeCor: "Lilás", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#796F8C", paginaCatalogo: 36 },
  { codigo: "IMX-GOLD-MAX-AZUL-NOTURNO", linha: "Gold Max", nomeCor: "Azul Noturno", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#13284F", paginaCatalogo: 37 },
  { codigo: "IMX-GOLD-MAX-AZUL-MARINHO", linha: "Gold Max", nomeCor: "Azul Marinho", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#133174", paginaCatalogo: 38 },
  { codigo: "IMX-GOLD-MAX-AZUL-RIVIERA", linha: "Gold Max", nomeCor: "Azul Riviera", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#0C4D84", paginaCatalogo: 39 },
  { codigo: "IMX-GOLD-MAX-AZUL-RECIFE", linha: "Gold Max", nomeCor: "Azul Recife", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#134DA9", paginaCatalogo: 40 },
  { codigo: "IMX-GOLD-MAX-AZUL-NEON", linha: "Gold Max", nomeCor: "Azul Neon", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#11357F", paginaCatalogo: 41 },
  { codigo: "IMX-GOLD-MAX-AZUL-CEU", linha: "Gold Max", nomeCor: "Azul Céu", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#1C5EB1", paginaCatalogo: 42 },
  { codigo: "IMX-GOLD-MAX-VERDE-CITRICO", linha: "Gold Max", nomeCor: "Verde Cítrico", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#88C94B", paginaCatalogo: 43 },
  { codigo: "IMX-GOLD-MAX-VERDE-ABACATE", linha: "Gold Max", nomeCor: "Verde Abacate", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#4DBC54", paginaCatalogo: 44 },
  { codigo: "IMX-GOLD-MAX-VERDE-AMAZONAS", linha: "Gold Max", nomeCor: "Verde Amazonas", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#2B9642", paginaCatalogo: 45 },
  { codigo: "IMX-GOLD-MAX-VERDE-BANDEIRA", linha: "Gold Max", nomeCor: "Verde Bandeira", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#207942", paginaCatalogo: 46 },
  { codigo: "IMX-GOLD-MAX-VERDE-ESCURO", linha: "Gold Max", nomeCor: "Verde Escuro", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#14311C", paginaCatalogo: 47 },
  { codigo: "IMX-GOLD-MAX-FOSCO-BRANCO", linha: "Gold Max Fosco", nomeCor: "Branco", tipoVinil: "polimerico", acabamento: "fosco", corHex: "#ABBCC2", paginaCatalogo: 49 },
  { codigo: "IMX-GOLD-MAX-FOSCO-GRAFITE", linha: "Gold Max Fosco", nomeCor: "Grafite", tipoVinil: "polimerico", acabamento: "fosco", corHex: "#3E494F", paginaCatalogo: 50 },
  { codigo: "IMX-GOLD-MAX-FOSCO-PRATA-ALUMINIO", linha: "Gold Max Fosco", nomeCor: "Prata Alumínio", tipoVinil: "polimerico", acabamento: "fosco", corHex: "#81959C", paginaCatalogo: 51 },
  { codigo: "IMX-GOLD-MAX-FOSCO-PRETO", linha: "Gold Max Fosco", nomeCor: "Preto", tipoVinil: "polimerico", acabamento: "fosco", corHex: "#0F141A", paginaCatalogo: 52 },
  { codigo: "IMX-GOLD-MAX-FOSCO-LARANJA-BOTANICO", linha: "Gold Max Fosco", nomeCor: "Laranja Botânico", tipoVinil: "polimerico", acabamento: "fosco", corHex: "#FF8542", paginaCatalogo: 53 },
  { codigo: "IMX-GOLD-MAX-FOSCO-VERMELHO-VIVO", linha: "Gold Max Fosco", nomeCor: "Vermelho Vivo", tipoVinil: "polimerico", acabamento: "fosco", corHex: "#BA2521", paginaCatalogo: 54 },
  { codigo: "IMX-GOLD-MAX-FOSCO-VERDE-BANDEIRA", linha: "Gold Max Fosco", nomeCor: "Verde Bandeira", tipoVinil: "polimerico", acabamento: "fosco", corHex: "#217B43", paginaCatalogo: 55 },
  { codigo: "IMX-SILVER-MAX-BRANCO", linha: "Silver Max", nomeCor: "Branco", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#EBEEED", paginaCatalogo: 58 },
  { codigo: "IMX-SILVER-MAX-CINZA-CLARO", linha: "Silver Max", nomeCor: "Cinza Claro", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#BDBCBC", paginaCatalogo: 59 },
  { codigo: "IMX-SILVER-MAX-PRATA-INFINITO", linha: "Silver Max", nomeCor: "Prata Infinito", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#96A6A7", paginaCatalogo: 60 },
  { codigo: "IMX-SILVER-MAX-CINZA-ESCURO", linha: "Silver Max", nomeCor: "Cinza Escuro", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#5D6A6B", paginaCatalogo: 61 },
  { codigo: "IMX-SILVER-MAX-PRETO-BRILHO", linha: "Silver Max", nomeCor: "Preto Brilho", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#05090C", paginaCatalogo: 62 },
  { codigo: "IMX-SILVER-MAX-AZUL-NOTURNO", linha: "Silver Max", nomeCor: "Azul Noturno", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#13284F", paginaCatalogo: 63 },
  { codigo: "IMX-SILVER-MAX-AZUL-MEDIO", linha: "Silver Max", nomeCor: "Azul Médio", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#12377A", paginaCatalogo: 64 },
  { codigo: "IMX-SILVER-MAX-AZUL-MARINHO", linha: "Silver Max", nomeCor: "Azul Marinho", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#133174", paginaCatalogo: 65 },
  { codigo: "IMX-SILVER-MAX-AZUL-CEU", linha: "Silver Max", nomeCor: "Azul Céu", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#39AFE2", paginaCatalogo: 66 },
  { codigo: "IMX-SILVER-MAX-MAGENTA", linha: "Silver Max", nomeCor: "Magenta", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#FD468E", paginaCatalogo: 67 },
  { codigo: "IMX-SILVER-MAX-VERMELHO-TOMATE", linha: "Silver Max", nomeCor: "Vermelho Tomate", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#FF4E3B", paginaCatalogo: 68 },
  { codigo: "IMX-SILVER-MAX-VERMELHO-VIVO", linha: "Silver Max", nomeCor: "Vermelho Vivo", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#FF2F1B", paginaCatalogo: 69 },
  { codigo: "IMX-SILVER-MAX-LARANJA", linha: "Silver Max", nomeCor: "Laranja", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#FF5B25", paginaCatalogo: 70 },
  { codigo: "IMX-SILVER-MAX-AMARELO-OURO", linha: "Silver Max", nomeCor: "Amarelo Ouro", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#FFA837", paginaCatalogo: 71 },
  { codigo: "IMX-SILVER-MAX-AMARELO-MEDIO", linha: "Silver Max", nomeCor: "Amarelo Médio", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#FFBC3C", paginaCatalogo: 72 },
  { codigo: "IMX-SILVER-MAX-OURO-SEMI-BRILHO", linha: "Silver Max", nomeCor: "Ouro Semi Brilho", tipoVinil: "polimerico", acabamento: "semi brilho", corHex: "#D19330", paginaCatalogo: 73 },
  { codigo: "IMX-SILVER-MAX-SUPER-BRILHO-BRANCO", linha: "Silver Max Super Brilho", nomeCor: "Branco", tipoVinil: "polimerico", acabamento: "super brilho", corHex: "#E1E3E5", paginaCatalogo: 75 },
  { codigo: "IMX-SILVER-MAX-SUPER-BRILHO-CINZA-CLARO", linha: "Silver Max Super Brilho", nomeCor: "Cinza Claro", tipoVinil: "polimerico", acabamento: "super brilho", corHex: "#909B9B", paginaCatalogo: 76 },
  { codigo: "IMX-SILVER-MAX-SUPER-BRILHO-CINZA-MEDIO", linha: "Silver Max Super Brilho", nomeCor: "Cinza Médio", tipoVinil: "polimerico", acabamento: "super brilho", corHex: "#3D3C3E", paginaCatalogo: 77 },
  { codigo: "IMX-SILVER-MAX-SUPER-BRILHO-CINZA-ESCURO", linha: "Silver Max Super Brilho", nomeCor: "Cinza Escuro", tipoVinil: "polimerico", acabamento: "super brilho", corHex: "#303739", paginaCatalogo: 78 },
  { codigo: "IMX-SILVER-MAX-SUPER-BRILHO-BLACK-PIANO", linha: "Silver Max Super Brilho", nomeCor: "Black Piano", tipoVinil: "polimerico", acabamento: "super brilho", corHex: "#000000", paginaCatalogo: 79 },
  { codigo: "IMX-SILVER-MAX-SUPER-BRILHO-BF-BLACK-PIANO", linha: "Silver Max Super Brilho", nomeCor: "BF Black Piano", tipoVinil: "polimerico", acabamento: "super brilho", corHex: "#000000", paginaCatalogo: 80 },
  { codigo: "IMX-SILVER-MAX-SUPER-BRILHO-AZUL-NOTURNO", linha: "Silver Max Super Brilho", nomeCor: "Azul Noturno", tipoVinil: "polimerico", acabamento: "super brilho", corHex: "#132A51", paginaCatalogo: 81 },
  { codigo: "IMX-SILVER-MAX-SUPER-BRILHO-AZUL-PROFUNDO", linha: "Silver Max Super Brilho", nomeCor: "Azul Profundo", tipoVinil: "polimerico", acabamento: "super brilho", corHex: "#0C3751", paginaCatalogo: 82 },
  { codigo: "IMX-SILVER-MAX-SUPER-BRILHO-AZUL-MEDIO", linha: "Silver Max Super Brilho", nomeCor: "Azul Médio", tipoVinil: "polimerico", acabamento: "super brilho", corHex: "#0C4D85", paginaCatalogo: 83 },
  { codigo: "IMX-SILVER-MAX-SUPER-BRILHO-AZUL-MARINHO", linha: "Silver Max Super Brilho", nomeCor: "Azul Marinho", tipoVinil: "polimerico", acabamento: "super brilho", corHex: "#133175", paginaCatalogo: 84 },
  { codigo: "IMX-SILVER-MAX-SUPER-BRILHO-AZUL-RECIFE", linha: "Silver Max Super Brilho", nomeCor: "Azul Recife", tipoVinil: "polimerico", acabamento: "super brilho", corHex: "#1B64B6", paginaCatalogo: 85 },
  { codigo: "IMX-SILVER-MAX-SUPER-BRILHO-AZUL-CEU", linha: "Silver Max Super Brilho", nomeCor: "Azul Céu", tipoVinil: "polimerico", acabamento: "super brilho", corHex: "#1C62B5", paginaCatalogo: 86 },
  { codigo: "IMX-SILVER-MAX-SUPER-BRILHO-AZUL-NEVE", linha: "Silver Max Super Brilho", nomeCor: "Azul Neve", tipoVinil: "polimerico", acabamento: "super brilho", corHex: "#84ADB7", paginaCatalogo: 87 },
  { codigo: "IMX-SILVER-MAX-SUPER-BRILHO-VERDE-MANJEIRICAO", linha: "Silver Max Super Brilho", nomeCor: "Verde Manjeiricão", tipoVinil: "polimerico", acabamento: "super brilho", corHex: "#6C8B3F", paginaCatalogo: 88 },
  { codigo: "IMX-SILVER-MAX-SUPER-BRILHO-VERDE-AMAZONAS", linha: "Silver Max Super Brilho", nomeCor: "Verde Amazonas", tipoVinil: "polimerico", acabamento: "super brilho", corHex: "#1A5B2C", paginaCatalogo: 89 },
  { codigo: "IMX-SILVER-MAX-SUPER-BRILHO-VERDE-BANDEIRA", linha: "Silver Max Super Brilho", nomeCor: "Verde Bandeira", tipoVinil: "polimerico", acabamento: "super brilho", corHex: "#207942", paginaCatalogo: 90 },
  { codigo: "IMX-SILVER-MAX-SUPER-BRILHO-VERDE-ESCURO", linha: "Silver Max Super Brilho", nomeCor: "Verde Escuro", tipoVinil: "polimerico", acabamento: "super brilho", corHex: "#1A301A", paginaCatalogo: 91 },
  { codigo: "IMX-SILVER-MAX-SUPER-BRILHO-AMARELO-OURO", linha: "Silver Max Super Brilho", nomeCor: "Amarelo Ouro", tipoVinil: "polimerico", acabamento: "super brilho", corHex: "#FFA937", paginaCatalogo: 92 },
  { codigo: "IMX-SILVER-MAX-SUPER-BRILHO-AMARELO-GEMA", linha: "Silver Max Super Brilho", nomeCor: "Amarelo Gema", tipoVinil: "polimerico", acabamento: "super brilho", corHex: "#FF6F29", paginaCatalogo: 93 },
  { codigo: "IMX-SILVER-MAX-SUPER-BRILHO-AMARELO-MEDIO", linha: "Silver Max Super Brilho", nomeCor: "Amarelo Médio", tipoVinil: "polimerico", acabamento: "super brilho", corHex: "#FFBC3C", paginaCatalogo: 94 },
  { codigo: "IMX-SILVER-MAX-SUPER-BRILHO-AMARELO-GIRAFA", linha: "Silver Max Super Brilho", nomeCor: "Amarelo Girafa", tipoVinil: "polimerico", acabamento: "super brilho", corHex: "#FF9B4D", paginaCatalogo: 95 },
  { codigo: "IMX-SILVER-MAX-SUPER-BRILHO-CREME", linha: "Silver Max Super Brilho", nomeCor: "Creme", tipoVinil: "polimerico", acabamento: "super brilho", corHex: "#CAA77B", paginaCatalogo: 96 },
  { codigo: "IMX-SILVER-MAX-SUPER-BRILHO-BEGE", linha: "Silver Max Super Brilho", nomeCor: "Bege", tipoVinil: "polimerico", acabamento: "super brilho", corHex: "#A7917E", paginaCatalogo: 97 },
  { codigo: "IMX-SILVER-MAX-SUPER-BRILHO-CARAMELO", linha: "Silver Max Super Brilho", nomeCor: "Caramelo", tipoVinil: "polimerico", acabamento: "super brilho", corHex: "#A9401C", paginaCatalogo: 98 },
  { codigo: "IMX-SILVER-MAX-SUPER-BRILHO-TERRA-MOLHADA", linha: "Silver Max Super Brilho", nomeCor: "Terra Molhada", tipoVinil: "polimerico", acabamento: "super brilho", corHex: "#8E2619", paginaCatalogo: 99 },
  { codigo: "IMX-SILVER-MAX-SUPER-BRILHO-MARROM", linha: "Silver Max Super Brilho", nomeCor: "Marrom", tipoVinil: "polimerico", acabamento: "super brilho", corHex: "#291210", paginaCatalogo: 100 },
  { codigo: "IMX-SILVER-MAX-SUPER-BRILHO-VINHO", linha: "Silver Max Super Brilho", nomeCor: "Vinho", tipoVinil: "polimerico", acabamento: "super brilho", corHex: "#2D0715", paginaCatalogo: 101 },
  { codigo: "IMX-SILVER-MAX-SUPER-BRILHO-VERMELHO-VIVO", linha: "Silver Max Super Brilho", nomeCor: "Vermelho Vivo", tipoVinil: "polimerico", acabamento: "super brilho", corHex: "#E63125", paginaCatalogo: 102 },
  { codigo: "IMX-SILVER-MAX-SUPER-BRILHO-VERMELHO-FOGO", linha: "Silver Max Super Brilho", nomeCor: "Vermelho Fogo", tipoVinil: "polimerico", acabamento: "super brilho", corHex: "#DB2C1A", paginaCatalogo: 103 },
  { codigo: "IMX-SILVER-MAX-SUPER-BRILHO-LARANJA", linha: "Silver Max Super Brilho", nomeCor: "Laranja", tipoVinil: "polimerico", acabamento: "super brilho", corHex: "#FF5B25", paginaCatalogo: 104 },
  { codigo: "IMX-SILVER-MAX-SUPER-BRILHO-MAGENTA", linha: "Silver Max Super Brilho", nomeCor: "Magenta", tipoVinil: "polimerico", acabamento: "super brilho", corHex: "#FD458D", paginaCatalogo: 105 },
  { codigo: "IMX-SILVER-MAX-SUPER-BRILHO-VIOLETA", linha: "Silver Max Super Brilho", nomeCor: "Violeta", tipoVinil: "polimerico", acabamento: "super brilho", corHex: "#212165", paginaCatalogo: 106 },
  { codigo: "IMX-SILVER-MAX-FOSCO-BRANCO", linha: "Silver Max Fosco", nomeCor: "Branco", tipoVinil: "polimerico", acabamento: "fosco", corHex: "#ECEFEE", paginaCatalogo: 108 },
  { codigo: "IMX-SILVER-MAX-FOSCO-LILAS-NEVOA", linha: "Silver Max Fosco", nomeCor: "Lilás Névoa", tipoVinil: "polimerico", acabamento: "fosco", corHex: "#8C6F85", paginaCatalogo: 109 },
  { codigo: "IMX-SILVER-MAX-FOSCO-COBRE-VECCHIO", linha: "Silver Max Fosco", nomeCor: "Cobre Vecchio", tipoVinil: "polimerico", acabamento: "fosco", corHex: "#A46B65", paginaCatalogo: 110 },
  { codigo: "IMX-SILVER-MAX-FOSCO-BEGE-TAUPE", linha: "Silver Max Fosco", nomeCor: "Bege Taupe", tipoVinil: "polimerico", acabamento: "fosco", corHex: "#87807D", paginaCatalogo: 112 },
  { codigo: "IMX-SILVER-MAX-FOSCO-CINZA-GLACIAL", linha: "Silver Max Fosco", nomeCor: "Cinza Glacial", tipoVinil: "polimerico", acabamento: "fosco", corHex: "#6E7B74", paginaCatalogo: 113 },
  { codigo: "IMX-SILVER-MAX-FOSCO-BEGE-PALHA", linha: "Silver Max Fosco", nomeCor: "Bege Palha", tipoVinil: "polimerico", acabamento: "fosco", corHex: "#A5A498", paginaCatalogo: 114 },
  { codigo: "IMX-SILVER-MAX-FOSCO-CINZA-NARDO", linha: "Silver Max Fosco", nomeCor: "Cinza Nardo", tipoVinil: "polimerico", acabamento: "fosco", corHex: "#3B4547", paginaCatalogo: 115 },
  { codigo: "IMX-SILVER-MAX-FOSCO-PRATA-INFINITO", linha: "Silver Max Fosco", nomeCor: "Prata Infinito", tipoVinil: "polimerico", acabamento: "fosco", corHex: "#919E9E", paginaCatalogo: 116 },
  { codigo: "IMX-SILVER-MAX-FOSCO-GRAFITE", linha: "Silver Max Fosco", nomeCor: "Grafite", tipoVinil: "polimerico", acabamento: "fosco", corHex: "#202629", paginaCatalogo: 117 },
  { codigo: "IMX-SILVER-MAX-FOSCO-PRETO", linha: "Silver Max Fosco", nomeCor: "Preto", tipoVinil: "polimerico", acabamento: "fosco", corHex: "#141D1D", paginaCatalogo: 118 },
  { codigo: "IMX-SILVER-MAX-FOSCO-PESSEGO", linha: "Silver Max Fosco", nomeCor: "Pêssego", tipoVinil: "polimerico", acabamento: "fosco", corHex: "#FF946F", paginaCatalogo: 119 },
  { codigo: "IMX-SILVER-MAX-FOSCO-VERDE-MENTA", linha: "Silver Max Fosco", nomeCor: "Verde Menta", tipoVinil: "polimerico", acabamento: "fosco", corHex: "#B5E2CD", paginaCatalogo: 120 },
  { codigo: "IMX-SILVER-MAX-FOSCO-VERDE-FROSTY", linha: "Silver Max Fosco", nomeCor: "Verde Frosty", tipoVinil: "polimerico", acabamento: "fosco", corHex: "#40564A", paginaCatalogo: 121 },
  { codigo: "IMX-SILVER-MAX-FOSCO-ACELGA", linha: "Silver Max Fosco", nomeCor: "Acelga", tipoVinil: "polimerico", acabamento: "fosco", corHex: "#898C63", paginaCatalogo: 122 },
  { codigo: "IMX-SILVER-MAX-FOSCO-AZUL-GLACIAL", linha: "Silver Max Fosco", nomeCor: "Azul Glacial", tipoVinil: "polimerico", acabamento: "fosco", corHex: "#649297", paginaCatalogo: 123 },
  { codigo: "IMX-SILVER-MAX-FOSCO-LAVANDA", linha: "Silver Max Fosco", nomeCor: "Lavanda", tipoVinil: "polimerico", acabamento: "fosco", corHex: "#6F7EA9", paginaCatalogo: 124 },
  { codigo: "IMX-SILVER-MAX-FOSCO-AZUL-HARMONIA", linha: "Silver Max Fosco", nomeCor: "Azul Harmonia", tipoVinil: "polimerico", acabamento: "fosco", corHex: "#496B89", paginaCatalogo: 125 },
  { codigo: "IMX-COLOR-MAX-PRETO-SUPER-BRILHO", linha: "Color Max", nomeCor: "Preto Super Brilho", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#030609", paginaCatalogo: 129 },
  { codigo: "IMX-COLOR-MAX-CINZA-CLARO", linha: "Color Max", nomeCor: "Cinza Claro", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#97A5A5", paginaCatalogo: 130 },
  { codigo: "IMX-COLOR-MAX-PRATA", linha: "Color Max", nomeCor: "Prata", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#97A4A4", paginaCatalogo: 131 },
  { codigo: "IMX-COLOR-MAX-CINZA-MEDIO", linha: "Color Max", nomeCor: "Cinza Médio", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#6E7D7E", paginaCatalogo: 132 },
  { codigo: "IMX-COLOR-MAX-CINZA-ESCURO", linha: "Color Max", nomeCor: "Cinza Escuro", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#40484A", paginaCatalogo: 133 },
  { codigo: "IMX-COLOR-MAX-PRETO", linha: "Color Max", nomeCor: "Preto", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#030609", paginaCatalogo: 134 },
  { codigo: "IMX-COLOR-MAX-MARROM", linha: "Color Max", nomeCor: "Marrom", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#5A2B17", paginaCatalogo: 135 },
  { codigo: "IMX-COLOR-MAX-OURO", linha: "Color Max", nomeCor: "Ouro", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#84541D", paginaCatalogo: 136 },
  { codigo: "IMX-COLOR-MAX-DOURADO", linha: "Color Max", nomeCor: "Dourado", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#977234", paginaCatalogo: 137 },
  { codigo: "IMX-COLOR-MAX-VERDE-ESCURO", linha: "Color Max", nomeCor: "Verde Escuro", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#233D1D", paginaCatalogo: 138 },
  { codigo: "IMX-COLOR-MAX-VERDE-AMAZONAS", linha: "Color Max", nomeCor: "Verde Amazonas", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#1E6530", paginaCatalogo: 139 },
  { codigo: "IMX-COLOR-MAX-VERDE-MACA", linha: "Color Max", nomeCor: "Verde Maçã", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#B3D677", paginaCatalogo: 140 },
  { codigo: "IMX-COLOR-MAX-VERDE-ABACATE", linha: "Color Max", nomeCor: "Verde Abacate", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#6DC45A", paginaCatalogo: 141 },
  { codigo: "IMX-COLOR-MAX-VERDE-BANDEIRA", linha: "Color Max", nomeCor: "Verde Bandeira", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#1C6333", paginaCatalogo: 142 },
  { codigo: "IMX-COLOR-MAX-VERDE-TURQUESA", linha: "Color Max", nomeCor: "Verde Turquesa", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#29888A", paginaCatalogo: 143 },
  { codigo: "IMX-COLOR-MAX-AZUL-CEU-INTENSO", linha: "Color Max", nomeCor: "Azul Céu Intenso", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#457AC1", paginaCatalogo: 144 },
  { codigo: "IMX-COLOR-MAX-AZUL-CEU", linha: "Color Max", nomeCor: "Azul Céu", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#2AA8DC", paginaCatalogo: 145 },
  { codigo: "IMX-COLOR-MAX-AZUL-MEDIO", linha: "Color Max", nomeCor: "Azul Médio", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#133375", paginaCatalogo: 146 },
  { codigo: "IMX-COLOR-MAX-AZUL-MARINHO", linha: "Color Max", nomeCor: "Azul Marinho", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#133276", paginaCatalogo: 147 },
  { codigo: "IMX-COLOR-MAX-AZUL-NOTURNO", linha: "Color Max", nomeCor: "Azul Noturno", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#112C53", paginaCatalogo: 148 },
  { codigo: "IMX-COLOR-MAX-MAGENTA", linha: "Color Max", nomeCor: "Magenta", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#FB42A0", paginaCatalogo: 149 },
  { codigo: "IMX-COLOR-MAX-ROSA-CLARO", linha: "Color Max", nomeCor: "Rosa Claro", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#FDACD2", paginaCatalogo: 150 },
  { codigo: "IMX-COLOR-MAX-TOMATE-CEREJA", linha: "Color Max", nomeCor: "Tomate Cereja", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#FE533F", paginaCatalogo: 151 },
  { codigo: "IMX-COLOR-MAX-VERMELHO-TOMATE", linha: "Color Max", nomeCor: "Vermelho Tomate", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#CC311C", paginaCatalogo: 152 },
  { codigo: "IMX-COLOR-MAX-VERMELHO-VIVO", linha: "Color Max", nomeCor: "Vermelho Vivo", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#9B1F1A", paginaCatalogo: 153 },
  { codigo: "IMX-COLOR-MAX-LARANJA", linha: "Color Max", nomeCor: "Laranja", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#D66B38", paginaCatalogo: 154 },
  { codigo: "IMX-COLOR-MAX-AMARELO-OURO", linha: "Color Max", nomeCor: "Amarelo Ouro", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#FFA636", paginaCatalogo: 155 },
  { codigo: "IMX-COLOR-MAX-AMARELO-MEDIO", linha: "Color Max", nomeCor: "Amarelo Médio", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#FDBD41", paginaCatalogo: 156 },
  { codigo: "IMX-COLOR-MAX-AMARELO-MILANO", linha: "Color Max", nomeCor: "Amarelo Milano", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#FFDB49", paginaCatalogo: 157 },
  { codigo: "IMX-COLOR-MAX-AMARELO-CITRUS", linha: "Color Max", nomeCor: "Amarelo Citrus", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#D2C96D", paginaCatalogo: 158 },
  { codigo: "IMX-COLOR-MAX-BEGE", linha: "Color Max", nomeCor: "Bege", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#FFF2C7", paginaCatalogo: 159 },
  { codigo: "IMX-COLOR-MAX-ESCOVADO-PRATA", linha: "Color Max", nomeCor: "Escovado Prata", tipoVinil: "polimerico", acabamento: "escovado", corHex: "#8A9697", paginaCatalogo: 128 },
  { codigo: "IMX-COLOR-MAX-CINZA-CLARO-FOSCO", linha: "Color Max", nomeCor: "Cinza Claro Fosco", tipoVinil: "polimerico", acabamento: "fosco", corHex: "#98A6A5", paginaCatalogo: 160 },
  { codigo: "IMX-COLOR-MAX-PRETO-FOSCO", linha: "Color Max", nomeCor: "Preto Fosco", tipoVinil: "polimerico", acabamento: "fosco", corHex: "#020407", paginaCatalogo: 161 },
  { codigo: "IMX-MAX-LUX-BRANCO", linha: "Max Lux", nomeCor: "Branco", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#EEF2F1", paginaCatalogo: 164 },
  { codigo: "IMX-MAX-LUX-VERMELHO-TOMATE", linha: "Max Lux", nomeCor: "Vermelho Tomate", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#C1261A", paginaCatalogo: 165 },
  { codigo: "IMX-MAX-LUX-VERMELHO-FOGO", linha: "Max Lux", nomeCor: "Vermelho Fogo", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#FF2E19", paginaCatalogo: 166 },
  { codigo: "IMX-MAX-LUX-LARANJA", linha: "Max Lux", nomeCor: "Laranja", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#FF7438", paginaCatalogo: 167 },
  { codigo: "IMX-MAX-LUX-AMARELO-MEDIO", linha: "Max Lux", nomeCor: "Amarelo Médio", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#FFC851", paginaCatalogo: 168 },
  { codigo: "IMX-MAX-LUX-VERDE-BANDEIRA", linha: "Max Lux", nomeCor: "Verde Bandeira", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#207336", paginaCatalogo: 169 },
  { codigo: "IMX-MAX-LUX-AZUL-VIVIDO", linha: "Max Lux", nomeCor: "Azul Vívido", tipoVinil: "polimerico", acabamento: "brilho", corHex: "#044FA8", paginaCatalogo: 170 },
  { codigo: "IMX-CRISTAL-COLOR-FUME-TRANSLUCIDO", linha: "Cristal Color", nomeCor: "Fumê", tipoVinil: "translucido", acabamento: "translúcido", corHex: "#27302F", paginaCatalogo: 173 },
  { codigo: "IMX-CRISTAL-COLOR-FUME-CLARO-TRANSLUCIDO", linha: "Cristal Color", nomeCor: "Fumê Claro", tipoVinil: "translucido", acabamento: "translúcido", corHex: "#52564E", paginaCatalogo: 174 },
];
