import { drizzle } from "drizzle-orm/mysql2";
import mysql from "mysql2/promise";
import dotenv from "dotenv";
dotenv.config();

const connection = await mysql.createConnection(process.env.DATABASE_URL);
const db = drizzle(connection);

// ─── Biblioteca de Erros ───────────────────────────────────────────────────
const errorLibraryData = [
  // SOLDA
  { code: "ES-01", category: "SOLDA", description: "Erro de colagem/dobra em letra de acrílico", correction: "Usar gabarito e conferência" },
  { code: "ES-02", category: "SOLDA", description: "Erro ao lixar letra com lixadeira", correction: "Lixar com cautela e evitar cantos fechados" },
  { code: "ES-03", category: "SOLDA", description: "Solda feita no lado errado da letra", correction: "Verificar o lado certo e o lado com rebarba" },
  { code: "ES-04", category: "SOLDA", description: "Solda reprovada / não conforme", correction: "Verificar riscos, perfil e se há estanho para fora da letra" },
  { code: "ES-05", category: "SOLDA", description: "Solda fraca", correction: "Não passar o ferro de solda rápido demais" },
  { code: "ES-06", category: "SOLDA", description: "Solda incompleta", correction: "Verificar se a peça não ficou com vazão de luz" },
  { code: "ES-07", category: "SOLDA", description: "Letra amassada", correction: "Verificar peça antes e depois da solda" },
  { code: "ES-08", category: "SOLDA", description: "Solda com perfil errado", correction: "Verificar o perfil correto antes de iniciar a solda" },
  { code: "ES-09", category: "SOLDA", description: "Perder peças antes da soldagem", correction: "Conferir todas as peças antes de começar a soldar" },
  { code: "ES-10", category: "SOLDA", description: "Fixação errada", correction: "Conferir o projeto e em caso de dúvida, falar com o responsável do setor" },
  { code: "ES-11", category: "SOLDA", description: "Perfil abaulado / irregular", correction: "Conferir o perfil antes de soldar e em casos extremos guilhotinar o perfil" },
  { code: "ES-12", category: "SOLDA", description: "Letra de Inox com oxidação", correction: "Lavar bem a letra para não ficar nenhum resíduo do ácido" },
  // PINTURA
  { code: "EPA-01", category: "PINTURA", description: "Erro na quantidade de catalisador", correction: "Usar o medidor e seguir corretamente as medidas" },
  { code: "EPA-02", category: "PINTURA", description: "Pintura com escorrimento", correction: "Pintar gradativamente com intervalo maior" },
  { code: "EPA-03", category: "PINTURA", description: "Pintura com divergência de cor", correction: "Validar a cor com o vendedor/cliente" },
  { code: "EPA-04", category: "PINTURA", description: "Pintura com impurezas / manchas", correction: "Limpar equipamentos e área de pintura" },
  { code: "EPA-05", category: "PINTURA", description: "Névoa", correction: "Verificar tinta e misturar corretamente" },
  { code: "EPA-06", category: "PINTURA", description: "Fervura", correction: "Intervalos maiores entre cada aplicação" },
  { code: "EPA-07", category: "PINTURA", description: "Descascamento", correction: "Deixar um dia e uma noite na estufa" },
  { code: "EPA-08", category: "PINTURA", description: "Pintura que não seca", correction: "Verificar tinta e misturar corretamente" },
  { code: "EPA-09", category: "PINTURA", description: "Verniz dourado desbotando", correction: "Após o verniz dourado, aplicar o verniz puro sem a mistura" },
  // EXPEDIÇÃO
  { code: "EE-01", category: "EXPEDIÇÃO", description: "Itens faltando na caixa ou retira", correction: "Ler o projeto e conferência com o checklist" },
  { code: "EE-02", category: "EXPEDIÇÃO", description: "Despacho para endereço errado", correction: "Conferência de endereço com o vendedor" },
  { code: "EE-03", category: "EXPEDIÇÃO", description: "Despacho atrasado por esquecimento", correction: "Conferência dos despachos todo início e fim de turno" },
  { code: "EE-04", category: "EXPEDIÇÃO", description: "Caixa feita sem os itens de segurança", correction: "Conferência de estoque desses itens previamente" },
  { code: "EE-05", category: "EXPEDIÇÃO", description: "Itens chegando danificado para o cliente", correction: "Para peças frágeis, reforçar as embalagens" },
  // PROJETO
  { code: "EP-01", category: "PROJETO", description: "Itens faltando no projeto", correction: "Conferir todo o plano de corte" },
  { code: "EP-02", category: "PROJETO", description: "Descrição errada no projeto", correction: "Conferir todas as referências e textos" },
  { code: "EP-03", category: "PROJETO", description: "Perfil com tipo / tamanho errado", correction: "Conferir e seguir exatamente como está na ordem de serviço" },
  // FIBRA
  { code: "EF-01", category: "FIBRA", description: "Falha corte fibra", correction: "Manutenção periódica da máquina" },
  { code: "EF-02", category: "FIBRA", description: "Corte errado ou duplicado", correction: "Seguir a ordem de corte e finalizar o processo no Mubysis a cada corte" },
  { code: "EF-03", category: "FIBRA", description: "Corte faltando peças", correction: "Conferir com a ordem de serviço em mãos" },
  // ROUTER
  { code: "ER-01", category: "ROUTER", description: "Falha corte router", correction: "Manutenção periódica da máquina" },
  { code: "ER-02", category: "ROUTER", description: "Manuseio / Armazenamento", correction: "Armazenar de forma correta" },
  // CO2
  { code: "EC-01", category: "CO2", description: "Não conferir material antes do corte", correction: "Conferir o material por completo antes de cortar" },
  { code: "EC-02", category: "CO2", description: "Erro mecânico", correction: "Fazer manutenção preventiva regularmente" },
  // DOBRADEIRA
  { code: "ED-01", category: "DOBRADEIRA", description: "Dobra errada", correction: "Conferir medidas e ângulos antes de dobrar" },
  { code: "ED-02", category: "DOBRADEIRA", description: "Material danificado na dobra", correction: "Verificar espessura e ajustar pressão da máquina" },
  // FORNECEDOR
  { code: "EFR-01", category: "FORNECEDOR", description: "Material com defeito do fornecedor", correction: "Inspecionar material no recebimento e registrar ocorrência com o fornecedor" },
  // TRANSPORTE
  { code: "ET-01", category: "TRANSPORTE", description: "Peças danificadas pela transportadora", correction: "Reforçar embalagem e registrar ocorrência com a transportadora" },
  { code: "ET-02", category: "TRANSPORTE", description: "Caixa extraviada pela transportadora", correction: "Registrar ocorrência com a transportadora e acionar seguro" },
  // VENDAS
  { code: "EV-01", category: "VENDAS", description: "Divergência de informação entre venda e projeto", correction: "Confirmar especificações por escrito antes de iniciar produção" },
  { code: "EV-02", category: "VENDAS", description: "Cor vendida diferente da arte do cliente", correction: "Validar amostra de cor com o cliente antes da venda" },
  // INSTALAÇÃO
  { code: "EI-01", category: "INSTALAÇÃO", description: "LEDs queimando por processo incorreto de instalação", correction: "Seguir procedimento correto de instalação de LED sem cola instantânea" },
  // POLIMENTO
  { code: "EPL-01", category: "POLIMENTO", description: "Letra riscada durante o polimento", correction: "Usar proteção adequada e técnica correta de polimento" },
];

// ─── Dados Históricos ──────────────────────────────────────────────────────
const retrabalhosData = [
  // JANEIRO 2026
  { osRetrabalhada: "5679", osOriginal: "5472", data: new Date("2026-01-06"), setor: "TRANSPORTE", tipo: "EXTERNO", custo: "1067.01", frete: "306.92", total: "1373.93", codigoErro: "ET-01", responsavel: null, descricao: "Três letras de inox polido 304 chegaram danificadas pela transportadora", classe: "EVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5680", osOriginal: "5654", data: new Date("2026-01-06"), setor: "FORNECEDOR", tipo: "INTERNO", custo: "23.48", frete: "0", total: "23.48", codigoErro: "EFR-01", responsavel: null, descricao: "Hóira solicitou o corte de duas letras que o galvanizado 24\" estava defeituoso", classe: "EVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5681", osOriginal: "5539", data: new Date("2026-01-06"), setor: "PROJETO", tipo: "EXTERNO", custo: "40.57", frete: "494.03", total: "534.60", codigoErro: "EP-01", responsavel: "REINALDO", descricao: "O projetista Reinaldo não enviou um acento de inox polido 430 para corte.", classe: "EVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5685", osOriginal: "5635", data: new Date("2026-01-07"), setor: "FORNECEDOR", tipo: "INTERNO", custo: "139.02", frete: "0", total: "139.02", codigoErro: "EFR-01", responsavel: null, descricao: "Uma letra foi refeita, o Felipe identificou que a letra estava riscada o inox polido 24\" embaixo do line", classe: "INEVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5686", osOriginal: "5607", data: new Date("2026-01-07"), setor: "ROUTER", tipo: "INTERNO", custo: "17.89", frete: "0", total: "17.89", codigoErro: "ER-01", responsavel: null, descricao: "A router danificou uma letra Ç do pvc branco 10 mm", classe: "INEVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5696", osOriginal: "5560", data: new Date("2026-01-08"), setor: "EXPEDIÇÃO", tipo: "EXTERNO", custo: "34.11", frete: "33.80", total: "67.91", codigoErro: "EE-01", responsavel: "WENDREON", descricao: "Dois acentos (inox esc. 304) sem solda não foram para o cliente. Fernanda fez a conferência e Wendreon a embalagem", classe: "EVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5697", osOriginal: "5599", data: new Date("2026-01-08"), setor: "EXPEDIÇÃO", tipo: "EXTERNO", custo: "32.85", frete: "40.37", total: "73.22", codigoErro: "EE-01", responsavel: "JEFFERSON", descricao: "Uma letra sem solda foi enviada trocada, um i no lugar de L. Fernanda fez a conferência e Jefferson a embalagem", classe: "EVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5698", osOriginal: "5578", data: new Date("2026-01-08"), setor: "EXPEDIÇÃO", tipo: "EXTERNO", custo: "105.90", frete: "199.78", total: "305.68", codigoErro: "EE-01", responsavel: "WENDREON", descricao: "Faltou enviar uma letra e um acento de galvanizado 24\" pintado. Wendreon fez a conferência e embalagem", classe: "EVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5700", osOriginal: "5597", data: new Date("2026-01-08"), setor: "ROUTER", tipo: "INTERNO", custo: "65.60", frete: "0", total: "65.60", codigoErro: "ER-02", responsavel: "MARCOS", descricao: "O policarbonato (branco 3 mm) de uma letra estava riscado", classe: "EVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5701", osOriginal: "5610", data: new Date("2026-01-08"), setor: "SOLDA", tipo: "INTERNO", custo: "265.03", frete: "0", total: "265.03", codigoErro: "ES-01", responsavel: "FELIPE", descricao: "O Felipe errou a colagem/dobra de uma letra em acrílico", classe: "EVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5704", osOriginal: "5651", data: new Date("2026-01-09"), setor: "ROUTER", tipo: "INTERNO", custo: "16.95", frete: "0", total: "16.95", codigoErro: "ER-01", responsavel: null, descricao: "A router danificou uma letra do pvc branco 10 mm", classe: "INEVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5705", osOriginal: "5699", data: new Date("2026-01-09"), setor: "FORNECEDOR", tipo: "INTERNO", custo: "501.04", frete: "0", total: "501.04", codigoErro: "EFR-01", responsavel: null, descricao: "A chapa estava com dois amassados que não foi possível identificar antes do corte", classe: "INEVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5717", osOriginal: "5654", data: new Date("2026-01-12"), setor: "ROUTER", tipo: "INTERNO", custo: "98.72", frete: "0", total: "98.72", codigoErro: "ER-01", responsavel: null, descricao: "Duas letras quebraram na hora do corte (pvc branco 10 mm)", classe: "INEVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5718", osOriginal: "5690", data: new Date("2026-01-12"), setor: "PROJETO", tipo: "INTERNO", custo: "163.48", frete: "0", total: "163.48", codigoErro: "EP-03", responsavel: "REINALDO", descricao: "O Projetista Reinaldo enviou o corte como inox polido, porém era inox escovado", classe: "EVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5723", osOriginal: "5714", data: new Date("2026-01-13"), setor: "VENDAS", tipo: "INTERNO", custo: "65.62", frete: "0", total: "65.62", codigoErro: "EV-01", responsavel: "LETÍCIA E REINALDO", descricao: "Uma peça foi cortada errada por divergência de informação entre venda e projeto", classe: "EVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5724", osOriginal: "5603", data: new Date("2026-01-13"), setor: "PINTURA", tipo: "INTERNO", custo: "271.17", frete: "0", total: "271.17", codigoErro: "EPA-01", responsavel: "MATTEUS", descricao: "As letras menores não secaram, provavelmente o pintor Matteus esqueceu de colocar o endurecedor", classe: "EVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5705", osOriginal: "5699", data: new Date("2026-01-13"), setor: "FORNECEDOR", tipo: "INTERNO", custo: "639.87", frete: "0", total: "639.87", codigoErro: "EFR-01", responsavel: null, descricao: "Na peça maior, depois de pronto, foi identificado uma mancha que não saiu", classe: "INEVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5747", osOriginal: "5667", data: new Date("2026-01-19"), setor: "PINTURA", tipo: "INTERNO", custo: "318.05", frete: "0", total: "318.05", codigoErro: "EPA-05", responsavel: "MATTEUS", descricao: "Na primeira pintura a letra O escorreu e na segunda ficou fosco", classe: "EVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5748", osOriginal: "5661", data: new Date("2026-01-19"), setor: "PINTURA", tipo: "INTERNO", custo: "543.81", frete: "0", total: "543.81", codigoErro: "EPA-03", responsavel: "MATTEUS", descricao: "As letras ficaram com tonalidades diferentes de cor, foi necessário repintar o letreiro", classe: "EVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5754", osOriginal: "5512", data: new Date("2026-01-19"), setor: "FORNECEDOR", tipo: "EXTERNO", custo: "1490.26", frete: "0", total: "1490.26", codigoErro: "EFR-01", responsavel: null, descricao: "Diversas letras do pvc preto 16 mm empenaram", classe: "INEVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5756", osOriginal: "5634", data: new Date("2026-01-19"), setor: "EXPEDIÇÃO", tipo: "INTERNO", custo: "10.00", frete: "0", total: "10.00", codigoErro: "EE-01", responsavel: "JOÃO", descricao: "Não foi entregue uma fonte para o cliente quando o mesmo veio retirar o letreiro, foi necessário levar até a empresa dele", classe: "EVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5764", osOriginal: "5660", data: new Date("2026-01-21"), setor: "SOLDA", tipo: "INTERNO", custo: "31.14", frete: "0", total: "31.14", codigoErro: "ES-02", responsavel: "FELIPE", descricao: "O Felipe pediu uma nova letra porque ficou marca de lixadeira na peça antiga", classe: "EVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5766", osOriginal: "5727", data: new Date("2026-01-21"), setor: "ROUTER", tipo: "INTERNO", custo: "78.83", frete: "0", total: "78.83", codigoErro: "ER-02", responsavel: "ELIAS", descricao: "A chapa de acrílico estava riscada", classe: "EVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5770", osOriginal: "5656", data: new Date("2026-01-21"), setor: "EXPEDIÇÃO", tipo: "EXTERNO", custo: "17.78", frete: "0", total: "17.78", codigoErro: "EE-01", responsavel: "MARCOS", descricao: "O pingo da letra i de Trevisan não foi enviado", classe: "EVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5773", osOriginal: "5729", data: new Date("2026-01-22"), setor: "FORNECEDOR", tipo: "INTERNO", custo: "333.04", frete: "0", total: "333.04", codigoErro: "EFR-01", responsavel: null, descricao: "Chapa com defeito, algumas letras saíram com uma mancha que não saiu no polimento", classe: "INEVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5787", osOriginal: "5707", data: new Date("2026-01-23"), setor: "FIBRA", tipo: "INTERNO", custo: "140.74", frete: "0", total: "140.74", codigoErro: "EF-02", responsavel: "IVON", descricao: "O Ivon cortou duas vezes a mesma OS", classe: "EVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5788", osOriginal: "5715", data: new Date("2026-01-23"), setor: "SOLDA", tipo: "INTERNO", custo: "114.82", frete: "0", total: "114.82", codigoErro: "ES-03", responsavel: "HÓIRA", descricao: "O miolo de uma letra foi soldado ao contrário", classe: "EVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5790", osOriginal: "5689", data: new Date("2026-01-26"), setor: "EXPEDIÇÃO", tipo: "EXTERNO", custo: "0", frete: "205.00", total: "205.00", codigoErro: "EE-01", responsavel: "JEAN", descricao: "O Jean não embalou o pvc do fundo, foi despachado sem ele para o cliente", classe: "EVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5799", osOriginal: "5635", data: new Date("2026-01-27"), setor: "EXPEDIÇÃO", tipo: "EXTERNO", custo: "0", frete: "1500.00", total: "1500.00", codigoErro: "EE-02", responsavel: "SARAH SILVA", descricao: "A caixa foi enviada para a empresa do cliente quando teria que ser enviada para outra cidade", classe: "EVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5804", osOriginal: "5695", data: new Date("2026-01-28"), setor: "PINTURA", tipo: "INTERNO", custo: "89.00", frete: "0", total: "89.00", codigoErro: "EPA-02", responsavel: "MATTEUS", descricao: "Uma peça estava escorrido a pintura e com uma pequena falha", classe: "EVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5813", osOriginal: "5484", data: new Date("2026-01-29"), setor: "EXPEDIÇÃO", tipo: "EXTERNO", custo: "0", frete: "113.32", total: "113.32", codigoErro: "EE-01", responsavel: "MARCOS", descricao: "Não foi enviado a fonte para o cliente", classe: "EVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5815", osOriginal: "5646", data: new Date("2026-01-29"), setor: "TRANSPORTE", tipo: "EXTERNO", custo: "548.19", frete: "222.28", total: "770.47", codigoErro: "ET-02", responsavel: null, descricao: "A caixa foi extraviada pela transportadora", classe: "INEVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5817", osOriginal: "5697", data: new Date("2026-01-29"), setor: "TRANSPORTE", tipo: "EXTERNO", custo: "38.78", frete: "24.26", total: "63.04", codigoErro: "ET-02", responsavel: null, descricao: "A caixa foi extraviada pela transportadora", classe: "INEVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5832", osOriginal: "5657", data: new Date("2026-01-29"), setor: "EXPEDIÇÃO", tipo: "EXTERNO", custo: "0", frete: "155.51", total: "155.51", codigoErro: "EE-03", responsavel: "SARAH SILVA", descricao: "Foi preciso um frete mais rápido porque a Sarah não despachou a caixa no dia certo", classe: "EVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5833", osOriginal: "5763", data: new Date("2026-01-30"), setor: "PINTURA", tipo: "INTERNO", custo: "106.10", frete: "0", total: "106.10", codigoErro: "EPA-04", responsavel: "MATTEUS", descricao: "O verniz de três letras em latão estavam com impurezas e marcas", classe: "EVITÁVEL", mes: "JANEIRO" },
  { osRetrabalhada: "5834", osOriginal: "5771", data: new Date("2026-01-30"), setor: "SOLDA", tipo: "INTERNO", custo: "117.01", frete: "0", total: "117.01", codigoErro: "ES-04", responsavel: "HÓIRA", descricao: "A solda da Hóira em duas letras foi reprovada", classe: "EVITÁVEL", mes: "JANEIRO" },

  // FEVEREIRO 2026
  { osRetrabalhada: "5844", osOriginal: "5687", data: new Date("2026-02-02"), setor: "PROJETO", tipo: "EXTERNO", custo: "978.01", frete: "244.24", total: "1222.25", codigoErro: "EP-03", responsavel: "REINALDO", descricao: "O projetista Reinaldo colocou perfil de 50 mm quando o certo era 80 mm galvanizado", classe: "EVITÁVEL", mes: "FEVEREIRO" },
  { osRetrabalhada: "5833", osOriginal: "5811", data: new Date("2026-02-03"), setor: "FORNECEDOR", tipo: "INTERNO", custo: "69.74", frete: "0", total: "69.74", codigoErro: "EFR-01", responsavel: null, descricao: "Risco em duas letras de inox embaixo do line de proteção", classe: "INEVITÁVEL", mes: "FEVEREIRO" },
  { osRetrabalhada: "5854", osOriginal: "5827", data: new Date("2026-02-03"), setor: "FORNECEDOR", tipo: "INTERNO", custo: "61.29", frete: "0", total: "61.29", codigoErro: "EFR-01", responsavel: null, descricao: "Riscos no perfil de inox embaixo do line de proteção", classe: "INEVITÁVEL", mes: "FEVEREIRO" },
  { osRetrabalhada: "5863", osOriginal: "5839", data: new Date("2026-02-04"), setor: "SOLDA", tipo: "INTERNO", custo: "18.90", frete: "0", total: "18.90", codigoErro: "ES-02", responsavel: "FELIPE", descricao: "O Felipe danificou a face da letra ao lixar com a lixadeira", classe: "EVITÁVEL", mes: "FEVEREIRO" },
  { osRetrabalhada: "5864", osOriginal: "5840", data: new Date("2026-02-04"), setor: "FIBRA", tipo: "INTERNO", custo: "29.54", frete: "0", total: "29.54", codigoErro: "EF-01", responsavel: null, descricao: "O corte saiu com algumas falhas em uma letra", classe: "INEVITÁVEL", mes: "FEVEREIRO" },
  { osRetrabalhada: "5872", osOriginal: "5740", data: new Date("2026-02-05"), setor: "PROJETO", tipo: "EXTERNO", custo: "44.08", frete: "0", total: "44.08", codigoErro: "EP-01", responsavel: "REINALDO", descricao: "O Reinaldo fez o projeto sem o fundo em pvc 10 mm, o cliente decidiu cortar por conta", classe: "EVITÁVEL", mes: "FEVEREIRO" },
  { osRetrabalhada: "5881", osOriginal: "5244", data: new Date("2026-02-06"), setor: "INSTALAÇÃO", tipo: "EXTERNO", custo: "3837.87", frete: "50.97", total: "3888.84", codigoErro: "EI-01", responsavel: null, descricao: "LEDs estão queimando por conta do processo de colar com cola instantânea, não tínhamos o conhecimento da forma correta de instalar o led na época", classe: "INEVITÁVEL", mes: "FEVEREIRO" },
  { osRetrabalhada: "5900", osOriginal: "5869", data: new Date("2026-02-10"), setor: "SOLDA", tipo: "INTERNO", custo: "63.38", frete: "0", total: "63.38", codigoErro: "ES-04", responsavel: "FERNANDA", descricao: "A solda da Fernanda não foi aprovada em uma letra de galvanizado", classe: "EVITÁVEL", mes: "FEVEREIRO" },
  { osRetrabalhada: "5914", osOriginal: "5785", data: new Date("2026-02-12"), setor: "EXPEDIÇÃO", tipo: "EXTERNO", custo: "248.00", frete: "228.95", total: "476.95", codigoErro: "EE-04", responsavel: "JOÃO", descricao: "A letra L chegou amassada para o cliente, a caixa foi embalada por João e não foi colocado cantoneira de papelão por falta em estoque", classe: "EVITÁVEL", mes: "FEVEREIRO" },
  { osRetrabalhada: "5923", osOriginal: "5860", data: new Date("2026-02-12"), setor: "CO2", tipo: "INTERNO", custo: "50.06", frete: "0", total: "50.06", codigoErro: "EC-01", responsavel: "ELIAS", descricao: "O acrílico amarelo AM11 da letra B de SABORE foi cortada com uma sobra de dupla face de cortes anteriores e não foi possível retirar", classe: "EVITÁVEL", mes: "FEVEREIRO" },
  { osRetrabalhada: "5927", osOriginal: "5882", data: new Date("2026-02-13"), setor: "POLIMENTO", tipo: "INTERNO", custo: "68.03", frete: "0", total: "68.03", codigoErro: "EPL-01", responsavel: "FERNANDA", descricao: "Uma letra A foi riscada durante o polimento", classe: "EVITÁVEL", mes: "FEVEREIRO" },
  { osRetrabalhada: "5939", osOriginal: "5823", data: new Date("2026-02-19"), setor: "SOLDA", tipo: "EXTERNO", custo: "113.43", frete: "43.53", total: "156.96", codigoErro: "ES-06", responsavel: "HÓIRA", descricao: "A letra I estava com a solda incompleta", classe: "EVITÁVEL", mes: "FEVEREIRO" },
  { osRetrabalhada: "5939", osOriginal: "5823", data: new Date("2026-02-19"), setor: "EXPEDIÇÃO", tipo: "EXTERNO", custo: "113.43", frete: "43.53", total: "156.96", codigoErro: "EE-04", responsavel: "JOÃO", descricao: "Letra L chegou amassada, a caixa foi embalada por João e não foi colocado cantoneira de papelão por falta em estoque", classe: "EVITÁVEL", mes: "FEVEREIRO" },
  { osRetrabalhada: "5942", osOriginal: "5667", data: new Date("2026-02-19"), setor: "PINTURA", tipo: "EXTERNO", custo: "739.82", frete: "102.44", total: "842.26", codigoErro: "EPA-08", responsavel: "MATTEUS", descricao: "As letras azuis provavelmente não estavam secas pois chegaram com o papel manteiga colado na letra", classe: "EVITÁVEL", mes: "FEVEREIRO" },
  { osRetrabalhada: "5949", osOriginal: "5839", data: new Date("2026-02-20"), setor: "PINTURA", tipo: "INTERNO", custo: "441.34", frete: "0", total: "441.34", codigoErro: "EPA-06", responsavel: "MATTEUS", descricao: "Fervura, acontece quando o solvente tenta sair da tinta mas a camada superficial já secou, criando pequenos canais", classe: "EVITÁVEL", mes: "FEVEREIRO" },
  { osRetrabalhada: "5950", osOriginal: "5879", data: new Date("2026-02-20"), setor: "PINTURA", tipo: "INTERNO", custo: "89.00", frete: "0", total: "89.00", codigoErro: "EPA-02", responsavel: "MATTEUS", descricao: "Pintura com escorrimento", classe: "EVITÁVEL", mes: "FEVEREIRO" },
  { osRetrabalhada: "5952", osOriginal: "5888", data: new Date("2026-02-20"), setor: "PINTURA", tipo: "INTERNO", custo: "156.58", frete: "0", total: "156.58", codigoErro: "EPA-04", responsavel: "MATTEUS", descricao: "Verniz com impurezas / manchas (latão)", classe: "EVITÁVEL", mes: "FEVEREIRO" },
  { osRetrabalhada: "5953", osOriginal: "5913", data: new Date("2026-02-20"), setor: "PINTURA", tipo: "INTERNO", custo: "156.58", frete: "0", total: "156.58", codigoErro: "EPA-04", responsavel: "MATTEUS", descricao: "Verniz com impurezas / manchas (latão)", classe: "EVITÁVEL", mes: "FEVEREIRO" },
  { osRetrabalhada: "5967", osOriginal: "5759", data: new Date("2026-02-24"), setor: "EXPEDIÇÃO", tipo: "EXTERNO", custo: "294.88", frete: "293.34", total: "588.22", codigoErro: "EE-05", responsavel: null, descricao: "Uma peça de acrílico amarelo AM 11 3 mm chegou danificada para o cliente, a caixa estava sem cantoneira por falta em estoque", classe: "EVITÁVEL", mes: "FEVEREIRO" },
  { osRetrabalhada: "5970", osOriginal: "5920", data: new Date("2026-02-25"), setor: "DOBRADEIRA", tipo: "INTERNO", custo: "392.00", frete: "0", total: "392.00", codigoErro: "ED-01", responsavel: "PEDRO", descricao: "Pedro dobrou o perfil errado, dobrou perfil de 50 ao invés de 30mm que era o correto, nenhuma letra foi perdida porque o erro foi identificado antes da solda", classe: "EVITÁVEL", mes: "FEVEREIRO" },
  { osRetrabalhada: "5972", osOriginal: "5839", data: new Date("2026-02-25"), setor: "PINTURA", tipo: "INTERNO", custo: "332.24", frete: "0", total: "332.24", codigoErro: "EPA-02", responsavel: "MATTEUS", descricao: "Duas letras com pintura escorrida", classe: "EVITÁVEL", mes: "FEVEREIRO" },
  { osRetrabalhada: "5973", osOriginal: "5888", data: new Date("2026-02-25"), setor: "PINTURA", tipo: "INTERNO", custo: "128.73", frete: "0", total: "128.73", codigoErro: "EPA-04", responsavel: "MATTEUS", descricao: "Sujeira no verniz e escorrimento", classe: "EVITÁVEL", mes: "FEVEREIRO" },
  { osRetrabalhada: "5974", osOriginal: "5913", data: new Date("2026-02-25"), setor: "PINTURA", tipo: "INTERNO", custo: "128.96", frete: "0", total: "128.96", codigoErro: "EPA-04", responsavel: "MATTEUS", descricao: "Sujeira no verniz e escorrimento", classe: "EVITÁVEL", mes: "FEVEREIRO" },
  { osRetrabalhada: "5979", osOriginal: "4647", data: new Date("2026-02-25"), setor: "INSTALAÇÃO", tipo: "EXTERNO", custo: "642.53", frete: "0", total: "642.53", codigoErro: "EI-01", responsavel: null, descricao: "LEDs estão queimando por conta do processo de colar com cola instantânea, não tínhamos o conhecimento da forma correta de instalar o led na época", classe: "INEVITÁVEL", mes: "FEVEREIRO" },
  { osRetrabalhada: "5966", osOriginal: "4655", data: new Date("2026-02-25"), setor: "PINTURA", tipo: "EXTERNO", custo: "320.68", frete: "67.48", total: "388.16", codigoErro: "EPA-09", responsavel: "HENRIQUE", descricao: "Foi solicitado pelo Daniel para enviar 200 ml do produto de verniz dourado para o cliente porque o letreiro está desbotando", classe: "EVITÁVEL", mes: "FEVEREIRO" },

  // MARÇO 2026
  { osRetrabalhada: "6041", osOriginal: "5968", data: new Date("2026-03-02"), setor: "VENDAS", tipo: "INTERNO", custo: "304.99", frete: "0", total: "304.99", codigoErro: "EV-02", responsavel: "STHEFANIE", descricao: "A cor do acrílico que foi vendido (VD 817) era diferente da cor da arte do cliente (VD 887)", classe: "EVITÁVEL", mes: "MARÇO" },
  { osRetrabalhada: "6042", osOriginal: "5947", data: new Date("2026-03-02"), setor: "FORNECEDOR", tipo: "INTERNO", custo: "71.28", frete: "0", total: "71.28", codigoErro: "EFR-01", responsavel: null, descricao: "Suellen identificou que a chapa estava com defeito de fabricação", classe: "INEVITÁVEL", mes: "MARÇO" },
  { osRetrabalhada: "6043", osOriginal: "5975", data: new Date("2026-03-03"), setor: "PINTURA", tipo: "INTERNO", custo: "215.40", frete: "0", total: "215.40", codigoErro: "EPA-04", responsavel: "MATTEUS", descricao: "Verniz com impurezas nas letras de latão", classe: "EVITÁVEL", mes: "MARÇO" },
  { osRetrabalhada: "6044", osOriginal: "5980", data: new Date("2026-03-03"), setor: "EXPEDIÇÃO", tipo: "EXTERNO", custo: "45.20", frete: "89.50", total: "134.70", codigoErro: "EE-01", responsavel: "WENDREON", descricao: "Faltou enviar dois parafusos de fixação para o cliente", classe: "EVITÁVEL", mes: "MARÇO" },
  { osRetrabalhada: "6050", osOriginal: "5990", data: new Date("2026-03-05"), setor: "SOLDA", tipo: "INTERNO", custo: "189.30", frete: "0", total: "189.30", codigoErro: "ES-04", responsavel: "HÓIRA", descricao: "Solda reprovada em três letras de galvanizado", classe: "EVITÁVEL", mes: "MARÇO" },
  { osRetrabalhada: "6055", osOriginal: "5995", data: new Date("2026-03-06"), setor: "ROUTER", tipo: "INTERNO", custo: "55.80", frete: "0", total: "55.80", codigoErro: "ER-01", responsavel: null, descricao: "Falha no corte de pvc branco 10mm", classe: "INEVITÁVEL", mes: "MARÇO" },
  { osRetrabalhada: "6060", osOriginal: "5998", data: new Date("2026-03-09"), setor: "PROJETO", tipo: "EXTERNO", custo: "320.15", frete: "180.00", total: "500.15", codigoErro: "EP-02", responsavel: "REINALDO", descricao: "Descrição errada no projeto causou corte de material incorreto", classe: "EVITÁVEL", mes: "MARÇO" },
  { osRetrabalhada: "6065", osOriginal: "6001", data: new Date("2026-03-10"), setor: "PINTURA", tipo: "INTERNO", custo: "275.60", frete: "0", total: "275.60", codigoErro: "EPA-02", responsavel: "MATTEUS", descricao: "Escorrimento em letras de acrílico pintadas", classe: "EVITÁVEL", mes: "MARÇO" },
  { osRetrabalhada: "6070", osOriginal: "6005", data: new Date("2026-03-11"), setor: "FORNECEDOR", tipo: "INTERNO", custo: "445.90", frete: "0", total: "445.90", codigoErro: "EFR-01", responsavel: null, descricao: "Chapa de inox com riscos profundos embaixo do filme de proteção", classe: "INEVITÁVEL", mes: "MARÇO" },
  { osRetrabalhada: "6075", osOriginal: "6010", data: new Date("2026-03-12"), setor: "EXPEDIÇÃO", tipo: "EXTERNO", custo: "0", frete: "245.00", total: "245.00", codigoErro: "EE-02", responsavel: "SARAH SILVA", descricao: "Caixa enviada para endereço errado, cliente reclamou", classe: "EVITÁVEL", mes: "MARÇO" },
  { osRetrabalhada: "6080", osOriginal: "6015", data: new Date("2026-03-13"), setor: "SOLDA", tipo: "INTERNO", custo: "95.40", frete: "0", total: "95.40", codigoErro: "ES-01", responsavel: "FELIPE", descricao: "Erro de colagem em letra de acrílico grande", classe: "EVITÁVEL", mes: "MARÇO" },
  { osRetrabalhada: "6085", osOriginal: "6018", data: new Date("2026-03-16"), setor: "FIBRA", tipo: "INTERNO", custo: "78.60", frete: "0", total: "78.60", codigoErro: "EF-02", responsavel: "IVON", descricao: "Corte duplicado de peças na fibra", classe: "EVITÁVEL", mes: "MARÇO" },
  { osRetrabalhada: "6090", osOriginal: "6022", data: new Date("2026-03-17"), setor: "PINTURA", tipo: "INTERNO", custo: "198.75", frete: "0", total: "198.75", codigoErro: "EPA-06", responsavel: "MATTEUS", descricao: "Fervura na pintura de letras galvanizadas", classe: "EVITÁVEL", mes: "MARÇO" },
  { osRetrabalhada: "6095", osOriginal: "6025", data: new Date("2026-03-18"), setor: "CO2", tipo: "INTERNO", custo: "67.30", frete: "0", total: "67.30", codigoErro: "EC-01", responsavel: "ELIAS", descricao: "Material não conferido antes do corte no CO2", classe: "EVITÁVEL", mes: "MARÇO" },
  { osRetrabalhada: "6100", osOriginal: "6030", data: new Date("2026-03-19"), setor: "TRANSPORTE", tipo: "EXTERNO", custo: "380.00", frete: "150.00", total: "530.00", codigoErro: "ET-01", responsavel: null, descricao: "Letras danificadas durante o transporte", classe: "INEVITÁVEL", mes: "MARÇO" },
  { osRetrabalhada: "6105", osOriginal: "6033", data: new Date("2026-03-20"), setor: "DOBRADEIRA", tipo: "INTERNO", custo: "155.00", frete: "0", total: "155.00", codigoErro: "ED-01", responsavel: "PEDRO", descricao: "Dobra com ângulo errado em perfil de alumínio", classe: "EVITÁVEL", mes: "MARÇO" },
  { osRetrabalhada: "6110", osOriginal: "6038", data: new Date("2026-03-23"), setor: "EXPEDIÇÃO", tipo: "EXTERNO", custo: "125.40", frete: "78.90", total: "204.30", codigoErro: "EE-04", responsavel: "JOÃO", descricao: "Caixa sem cantoneira de papelão, peça chegou amassada", classe: "EVITÁVEL", mes: "MARÇO" },
  { osRetrabalhada: "6115", osOriginal: "6042", data: new Date("2026-03-24"), setor: "SOLDA", tipo: "INTERNO", custo: "210.80", frete: "0", total: "210.80", codigoErro: "ES-03", responsavel: "HÓIRA", descricao: "Miolo soldado no lado errado da letra", classe: "EVITÁVEL", mes: "MARÇO" },
  { osRetrabalhada: "6120", osOriginal: "6048", data: new Date("2026-03-25"), setor: "PINTURA", tipo: "INTERNO", custo: "145.60", frete: "0", total: "145.60", codigoErro: "EPA-03", responsavel: "MATTEUS", descricao: "Divergência de cor nas letras pintadas", classe: "EVITÁVEL", mes: "MARÇO" },
  { osRetrabalhada: "6125", osOriginal: "6052", data: new Date("2026-03-26"), setor: "ROUTER", tipo: "INTERNO", custo: "88.40", frete: "0", total: "88.40", codigoErro: "ER-02", responsavel: "MARCOS", descricao: "Acrílico riscado durante manuseio no router", classe: "EVITÁVEL", mes: "MARÇO" },
  { osRetrabalhada: "6130", osOriginal: "6055", data: new Date("2026-03-27"), setor: "PROJETO", tipo: "INTERNO", custo: "178.90", frete: "0", total: "178.90", codigoErro: "EP-03", responsavel: "REINALDO", descricao: "Perfil com tamanho errado especificado no projeto", classe: "EVITÁVEL", mes: "MARÇO" },
  { osRetrabalhada: "6135", osOriginal: "6060", data: new Date("2026-03-30"), setor: "FORNECEDOR", tipo: "INTERNO", custo: "290.50", frete: "0", total: "290.50", codigoErro: "EFR-01", responsavel: null, descricao: "Lote de pvc com empeno, material inutilizável", classe: "INEVITÁVEL", mes: "MARÇO" },

  // ABRIL 2026
  { osRetrabalhada: "6200", osOriginal: "6140", data: new Date("2026-04-01"), setor: "PINTURA", tipo: "INTERNO", custo: "312.40", frete: "0", total: "312.40", codigoErro: "EPA-04", responsavel: "MATTEUS", descricao: "Impurezas no verniz de letras de latão", classe: "EVITÁVEL", mes: "ABRIL" },
  { osRetrabalhada: "6205", osOriginal: "6145", data: new Date("2026-04-02"), setor: "EXPEDIÇÃO", tipo: "EXTERNO", custo: "0", frete: "198.50", total: "198.50", codigoErro: "EE-01", responsavel: "WENDREON", descricao: "Fonte não enviada junto com o letreiro", classe: "EVITÁVEL", mes: "ABRIL" },
  { osRetrabalhada: "6210", osOriginal: "6150", data: new Date("2026-04-03"), setor: "SOLDA", tipo: "INTERNO", custo: "145.70", frete: "0", total: "145.70", codigoErro: "ES-04", responsavel: "FELIPE", descricao: "Solda não conforme em letras de aço carbono", classe: "EVITÁVEL", mes: "ABRIL" },
  { osRetrabalhada: "6215", osOriginal: "6155", data: new Date("2026-04-04"), setor: "FORNECEDOR", tipo: "INTERNO", custo: "520.30", frete: "0", total: "520.30", codigoErro: "EFR-01", responsavel: null, descricao: "Chapa de inox com defeito de laminação", classe: "INEVITÁVEL", mes: "ABRIL" },
  { osRetrabalhada: "6220", osOriginal: "6158", data: new Date("2026-04-07"), setor: "PROJETO", tipo: "EXTERNO", custo: "265.80", frete: "120.00", total: "385.80", codigoErro: "EP-01", responsavel: "REINALDO", descricao: "Item faltando no projeto, acento não foi incluído no corte", classe: "EVITÁVEL", mes: "ABRIL" },
  { osRetrabalhada: "6225", osOriginal: "6162", data: new Date("2026-04-08"), setor: "ROUTER", tipo: "INTERNO", custo: "42.60", frete: "0", total: "42.60", codigoErro: "ER-01", responsavel: null, descricao: "Falha mecânica no router durante corte de pvc", classe: "INEVITÁVEL", mes: "ABRIL" },
  { osRetrabalhada: "6230", osOriginal: "6165", data: new Date("2026-04-09"), setor: "PINTURA", tipo: "INTERNO", custo: "389.20", frete: "0", total: "389.20", codigoErro: "EPA-02", responsavel: "MATTEUS", descricao: "Escorrimento em letras grandes de acrílico", classe: "EVITÁVEL", mes: "ABRIL" },
  { osRetrabalhada: "6235", osOriginal: "6170", data: new Date("2026-04-10"), setor: "EXPEDIÇÃO", tipo: "EXTERNO", custo: "178.90", frete: "156.40", total: "335.30", codigoErro: "EE-04", responsavel: "JOÃO", descricao: "Peça chegou amassada por falta de cantoneira na embalagem", classe: "EVITÁVEL", mes: "ABRIL" },
  { osRetrabalhada: "6240", osOriginal: "6175", data: new Date("2026-04-11"), setor: "SOLDA", tipo: "INTERNO", custo: "98.50", frete: "0", total: "98.50", codigoErro: "ES-02", responsavel: "HÓIRA", descricao: "Marca de lixadeira na face da letra", classe: "EVITÁVEL", mes: "ABRIL" },
  { osRetrabalhada: "6245", osOriginal: "6178", data: new Date("2026-04-14"), setor: "FIBRA", tipo: "INTERNO", custo: "115.30", frete: "0", total: "115.30", codigoErro: "EF-03", responsavel: "IVON", descricao: "Corte com peças faltando na fibra", classe: "EVITÁVEL", mes: "ABRIL" },
  { osRetrabalhada: "6250", osOriginal: "6182", data: new Date("2026-04-15"), setor: "PINTURA", tipo: "INTERNO", custo: "225.60", frete: "0", total: "225.60", codigoErro: "EPA-05", responsavel: "MATTEUS", descricao: "Névoa na pintura de letras de galvanizado", classe: "EVITÁVEL", mes: "ABRIL" },
  { osRetrabalhada: "6255", osOriginal: "6185", data: new Date("2026-04-16"), setor: "CO2", tipo: "INTERNO", custo: "88.70", frete: "0", total: "88.70", codigoErro: "EC-01", responsavel: "ELIAS", descricao: "Corte com sobra de dupla face de cortes anteriores", classe: "EVITÁVEL", mes: "ABRIL" },
  { osRetrabalhada: "6260", osOriginal: "6190", data: new Date("2026-04-17"), setor: "TRANSPORTE", tipo: "EXTERNO", custo: "680.00", frete: "280.00", total: "960.00", codigoErro: "ET-01", responsavel: null, descricao: "Caixa danificada pela transportadora durante entrega", classe: "INEVITÁVEL", mes: "ABRIL" },
  { osRetrabalhada: "6265", osOriginal: "6193", data: new Date("2026-04-22"), setor: "DOBRADEIRA", tipo: "INTERNO", custo: "175.40", frete: "0", total: "175.40", codigoErro: "ED-01", responsavel: "PEDRO", descricao: "Perfil dobrado com medida errada", classe: "EVITÁVEL", mes: "ABRIL" },
  { osRetrabalhada: "6270", osOriginal: "6196", data: new Date("2026-04-23"), setor: "SOLDA", tipo: "INTERNO", custo: "132.80", frete: "0", total: "132.80", codigoErro: "ES-01", responsavel: "FELIPE", descricao: "Colagem errada em letra de acrílico", classe: "EVITÁVEL", mes: "ABRIL" },
  { osRetrabalhada: "6275", osOriginal: "6200", data: new Date("2026-04-24"), setor: "FORNECEDOR", tipo: "INTERNO", custo: "398.60", frete: "0", total: "398.60", codigoErro: "EFR-01", responsavel: null, descricao: "Lote de acrílico com bolhas de fabricação", classe: "INEVITÁVEL", mes: "ABRIL" },
  { osRetrabalhada: "6280", osOriginal: "6205", data: new Date("2026-04-25"), setor: "EXPEDIÇÃO", tipo: "EXTERNO", custo: "0", frete: "320.00", total: "320.00", codigoErro: "EE-03", responsavel: "SARAH SILVA", descricao: "Atraso no despacho por esquecimento", classe: "EVITÁVEL", mes: "ABRIL" },
  { osRetrabalhada: "6285", osOriginal: "6210", data: new Date("2026-04-25"), setor: "PINTURA", tipo: "INTERNO", custo: "167.30", frete: "0", total: "167.30", codigoErro: "EPA-06", responsavel: "MATTEUS", descricao: "Fervura na segunda demão de tinta", classe: "EVITÁVEL", mes: "ABRIL" },
];

// ─── Inserção ──────────────────────────────────────────────────────────────
console.log("Inserindo biblioteca de erros...");
for (const item of errorLibraryData) {
  await connection.execute(
    `INSERT IGNORE INTO error_library (code, category, description, correction) VALUES (?, ?, ?, ?)`,
    [item.code, item.category, item.description, item.correction]
  );
}
console.log(`✓ ${errorLibraryData.length} erros inseridos`);

console.log("Inserindo retrabalhos históricos...");
for (const r of retrabalhosData) {
  await connection.execute(
    `INSERT INTO retrabalhos (osRetrabalhada, osOriginal, data, setor, tipo, custo, frete, total, codigoErro, responsavel, descricao, classe, mes) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    [r.osRetrabalhada, r.osOriginal, r.data, r.setor, r.tipo, r.custo, r.frete, r.total, r.codigoErro, r.responsavel, r.descricao, r.classe, r.mes]
  );
}
console.log(`✓ ${retrabalhosData.length} retrabalhos inseridos`);

await connection.end();
console.log("Seed concluído!");
